name: Test01

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches: []

jobs:
  test:
    name: Test
    runs-on: windows-2016
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: echo "Runing Tests"

